/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Publication } from "./Publication";
export * as factories from "./factories";
export { Publication__factory } from "./factories/Publication__factory";
