/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Journal } from "./Journal";
export * as factories from "./factories";
export { Journal__factory } from "./factories/Journal__factory";
